-- Generated by Oracle SQL Developer Data Modeler 20.4.0.374.0801
--   at:        2021-04-27 18:36:11 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
--   studentid: 30884128
--   name:      George Tan Juan Sheng

set echo on
spool ad_schema_output.txt

DROP TABLE animal CASCADE CONSTRAINTS;

DROP TABLE animal_type CASCADE CONSTRAINTS;

DROP TABLE clinic CASCADE CONSTRAINTS;

DROP TABLE drug CASCADE CONSTRAINTS;

DROP TABLE owner CASCADE CONSTRAINTS;

DROP TABLE prescription CASCADE CONSTRAINTS;

DROP TABLE rove CASCADE CONSTRAINTS;

DROP TABLE service CASCADE CONSTRAINTS;

DROP TABLE service_details CASCADE CONSTRAINTS;

DROP TABLE vet CASCADE CONSTRAINTS;

DROP TABLE vet_specialisation CASCADE CONSTRAINTS;

DROP TABLE visit CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE animal (
    animal_id         NUMBER(7) NOT NULL,
    animal_gender     CHAR(1) NOT NULL,
    animal_name       VARCHAR2(50) NOT NULL,
    animal_birthdate  DATE NOT NULL,
    animal_deceased   CHAR(1) NOT NULL,
    owner_id          NUMBER(7) NOT NULL,
    atype_id          NUMBER(7) NOT NULL
);

ALTER TABLE animal
    ADD CONSTRAINT chk_animal_gender CHECK ( animal_gender IN ( 'F', 'M' ) );

ALTER TABLE animal
    ADD CONSTRAINT chk_animal_deceased CHECK ( animal_deceased IN ( 'N', 'Y' ) );

COMMENT ON COLUMN animal.animal_id IS
    'animal id';

COMMENT ON COLUMN animal.animal_gender IS
    'animal gender (M,F)';

COMMENT ON COLUMN animal.animal_name IS
    'animal name';

COMMENT ON COLUMN animal.animal_birthdate IS
    'animal birthdate ';

COMMENT ON COLUMN animal.animal_deceased IS
    'animal deceased or not (Y/N)';

COMMENT ON COLUMN animal.owner_id IS
    'owner id';

COMMENT ON COLUMN animal.atype_id IS
    'animal type id';

ALTER TABLE animal ADD CONSTRAINT animal_pk PRIMARY KEY ( animal_id );

CREATE TABLE animal_type (
    atype_id    NUMBER(7) NOT NULL,
    atype_name  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN animal_type.atype_id IS
    'animal type id';

COMMENT ON COLUMN animal_type.atype_name IS
    'animal type name';

ALTER TABLE animal_type ADD CONSTRAINT animal_type_pk PRIMARY KEY ( atype_id );

ALTER TABLE animal_type ADD CONSTRAINT un_animal_type UNIQUE ( atype_name );

CREATE TABLE clinic (
    clinic_id       NUMBER(10) NOT NULL,
    clinic_name     VARCHAR2(50) NOT NULL,
    clinic_address  VARCHAR2(50) NOT NULL,
    clinic_phoneno  CHAR(10) NOT NULL
);

COMMENT ON COLUMN clinic.clinic_id IS
    'clinic id';

COMMENT ON COLUMN clinic.clinic_name IS
    'clinic name';

COMMENT ON COLUMN clinic.clinic_address IS
    'clinic address';

COMMENT ON COLUMN clinic.clinic_phoneno IS
    'clinic phone number';

ALTER TABLE clinic ADD CONSTRAINT clinic_pk PRIMARY KEY ( clinic_id );

CREATE TABLE drug (
    drug_id                  NUMBER(4) NOT NULL,
    drug_name                VARCHAR2(50) NOT NULL,
    drug_usage_instructions  VARCHAR2(100) NOT NULL,
    drug_standard_cost       NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN drug.drug_id IS
    'drug id';

COMMENT ON COLUMN drug.drug_name IS
    'drug name';

COMMENT ON COLUMN drug.drug_usage_instructions IS
    'drug usage instructions';

COMMENT ON COLUMN drug.drug_standard_cost IS
    'drug standard cost';

ALTER TABLE drug ADD CONSTRAINT drug_pk PRIMARY KEY ( drug_id );

CREATE TABLE owner (
    owner_id        NUMBER(7) NOT NULL,
    owner_givname   VARCHAR2(50) NOT NULL,
    owner_famname   VARCHAR2(50) NOT NULL,
    owner_street    VARCHAR2(30) NOT NULL,
    owner_town      VARCHAR2(30) NOT NULL,
    owner_postcode  CHAR(4) NOT NULL,
    owner_phoneno   CHAR(10),
    vet_id          NUMBER(7) NOT NULL
);

COMMENT ON COLUMN owner.owner_id IS
    'owner id';

COMMENT ON COLUMN owner.owner_givname IS
    'owner given name';

COMMENT ON COLUMN owner.owner_famname IS
    'owner family name';

COMMENT ON COLUMN owner.owner_street IS
    'owner address street';

COMMENT ON COLUMN owner.owner_town IS
    'owner address town ';

COMMENT ON COLUMN owner.owner_postcode IS
    'owner address post code';

COMMENT ON COLUMN owner.owner_phoneno IS
    'owner phone number';

COMMENT ON COLUMN owner.vet_id IS
    'vet id';

ALTER TABLE owner ADD CONSTRAINT owner_pk PRIMARY KEY ( owner_id );

CREATE TABLE prescription (
    visit_id                       NUMBER(7) NOT NULL,
    drug_id                        NUMBER(4) NOT NULL,
    prescription_drug_qtysupplied  NUMBER(5),
    prescription_drug_cost         NUMBER(6, 2) NOT NULL,
    prescription_drug_dose         VARCHAR2(20) NOT NULL,
    prescription_freq_admin        VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN prescription.visit_id IS
    'surrgoate visit id';

COMMENT ON COLUMN prescription.drug_id IS
    'drug id';

COMMENT ON COLUMN prescription.prescription_drug_qtysupplied IS
    'prescription drug quantity supplied';

COMMENT ON COLUMN prescription.prescription_drug_cost IS
    'prescription final drug cost  (may been modified by vet)';

COMMENT ON COLUMN prescription.prescription_drug_dose IS
    'prescription drug dose';

COMMENT ON COLUMN prescription.prescription_freq_admin IS
    'prescription frequency administration';

ALTER TABLE prescription ADD CONSTRAINT prescription_pk PRIMARY KEY ( drug_id,
                                                                      visit_id );

CREATE TABLE rove (
    vet_id          NUMBER(7) NOT NULL,
    clinic_id       NUMBER(10) NOT NULL,
    rove_vet_count  NUMBER(7) NOT NULL
);

COMMENT ON COLUMN rove.vet_id IS
    'vet id';

COMMENT ON COLUMN rove.clinic_id IS
    'clinic id';

COMMENT ON COLUMN rove.rove_vet_count IS
    'rove vet count, how many times a vet serviced a visit at clinics which are not their home clinic ';

ALTER TABLE rove ADD CONSTRAINT rove_pk PRIMARY KEY ( vet_id,
                                                      clinic_id );

CREATE TABLE service (
    service_code  VARCHAR2(10) NOT NULL,
    visit_id      NUMBER(7) NOT NULL,
    service_cost  NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN service.service_code IS
    'service code';

COMMENT ON COLUMN service.visit_id IS
    'surrgoate visit id';

COMMENT ON COLUMN service.service_cost IS
    'service cost';

ALTER TABLE service ADD CONSTRAINT service_pk PRIMARY KEY ( service_code,
                                                            visit_id );

CREATE TABLE service_details (
    service_code           VARCHAR2(10) NOT NULL,
    service_description    VARCHAR2(50) NOT NULL,
    service_standard_cost  NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN service_details.service_code IS
    'service code';

COMMENT ON COLUMN service_details.service_description IS
    'service description';

COMMENT ON COLUMN service_details.service_standard_cost IS
    'service standard cost';

ALTER TABLE service_details ADD CONSTRAINT service_details_pk PRIMARY KEY ( service_code );

CREATE TABLE vet (
    vet_id             NUMBER(7) NOT NULL,
    vet_title          VARCHAR2(10) NOT NULL,
    vet_givname        VARCHAR2(50) NOT NULL,
    vet_famname        VARCHAR2(50) NOT NULL,
    vet_phoneno        CHAR(10) NOT NULL,
    vet_date_employed  DATE NOT NULL,
    clinic_id          NUMBER(10) NOT NULL,
    vspecial_area_id   NUMBER(7)
);

COMMENT ON COLUMN vet.vet_id IS
    'vet id';

COMMENT ON COLUMN vet.vet_title IS
    'vet title ';

COMMENT ON COLUMN vet.vet_givname IS
    'vet given name';

COMMENT ON COLUMN vet.vet_famname IS
    'vet family name';

COMMENT ON COLUMN vet.vet_phoneno IS
    'vet phone number';

COMMENT ON COLUMN vet.vet_date_employed IS
    'vet date employed';

COMMENT ON COLUMN vet.clinic_id IS
    'clinic id';

COMMENT ON COLUMN vet.vspecial_area_id IS
    'vet specialised area id';

ALTER TABLE vet ADD CONSTRAINT vet_pk PRIMARY KEY ( vet_id );

CREATE TABLE vet_specialisation (
    vspecial_area_id    NUMBER(7) NOT NULL,
    vspecial_area_name  VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN vet_specialisation.vspecial_area_id IS
    'vet specialised area id';

COMMENT ON COLUMN vet_specialisation.vspecial_area_name IS
    'vet specialised area name';

ALTER TABLE vet_specialisation ADD CONSTRAINT vet_specialisation_pk PRIMARY KEY (
vspecial_area_id );

ALTER TABLE vet_specialisation ADD CONSTRAINT un_vspecial_area_name UNIQUE ( vspecial_area_name );

CREATE TABLE visit (
    visit_id               NUMBER(7) NOT NULL,
    visit_datetime         DATE NOT NULL,
    visit_total_amount     NUMBER(7, 2) NOT NULL,
    visit_paidby           CHAR(1) NOT NULL,
    visit_length           VARCHAR2(30) NOT NULL,
    visit_condition_notes  VARCHAR2(100) NOT NULL,
    vet_id                 NUMBER(7) NOT NULL,
    animal_id              NUMBER(7) NOT NULL,
    clinic_id              NUMBER(10) NOT NULL,
    visit_id_follow_up     NUMBER(7)
);

ALTER TABLE visit
    ADD CONSTRAINT chk_visit_paidby CHECK ( visit_paidby IN ( 'C', 'E' ) );

COMMENT ON COLUMN visit.visit_id IS
    'surrgoate visit id';

COMMENT ON COLUMN visit.visit_datetime IS
    'visit datetime';

COMMENT ON COLUMN visit.visit_total_amount IS
    'visit total amount paid';

COMMENT ON COLUMN visit.visit_paidby IS
    'visit paid by method (C/E)';

COMMENT ON COLUMN visit.visit_length IS
    'visit length';

COMMENT ON COLUMN visit.visit_condition_notes IS
    'visit condition notes';

COMMENT ON COLUMN visit.vet_id IS
    'vet id';

COMMENT ON COLUMN visit.animal_id IS
    'animal id';

COMMENT ON COLUMN visit.clinic_id IS
    'clinic id';

COMMENT ON COLUMN visit.visit_id_follow_up IS
    'surrgoate visit id';

ALTER TABLE visit ADD CONSTRAINT visit_pk PRIMARY KEY ( visit_id );

ALTER TABLE visit ADD CONSTRAINT un_vet_id_visit_datetime UNIQUE ( visit_datetime,
                                                                   vet_id );

ALTER TABLE animal
    ADD CONSTRAINT animal_type_animal FOREIGN KEY ( atype_id )
        REFERENCES animal_type ( atype_id );

ALTER TABLE visit
    ADD CONSTRAINT animal_visit FOREIGN KEY ( animal_id )
        REFERENCES animal ( animal_id );

ALTER TABLE rove
    ADD CONSTRAINT clinic_rove FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE vet
    ADD CONSTRAINT clinic_vet_assigns FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE visit
    ADD CONSTRAINT clinic_visit FOREIGN KEY ( clinic_id )
        REFERENCES clinic ( clinic_id );

ALTER TABLE prescription
    ADD CONSTRAINT drug_prescription FOREIGN KEY ( drug_id )
        REFERENCES drug ( drug_id );

ALTER TABLE animal
    ADD CONSTRAINT owner_animal FOREIGN KEY ( owner_id )
        REFERENCES owner ( owner_id );

ALTER TABLE service
    ADD CONSTRAINT service_details_service FOREIGN KEY ( service_code )
        REFERENCES service_details ( service_code );

ALTER TABLE owner
    ADD CONSTRAINT vet_owner FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE rove
    ADD CONSTRAINT vet_rove FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE vet
    ADD CONSTRAINT "VET_SPECIALIA\SATION_VET" FOREIGN KEY ( vspecial_area_id )
        REFERENCES vet_specialisation ( vspecial_area_id );

ALTER TABLE visit
    ADD CONSTRAINT vet_visit FOREIGN KEY ( vet_id )
        REFERENCES vet ( vet_id );

ALTER TABLE prescription
    ADD CONSTRAINT visit_prescription FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE service
    ADD CONSTRAINT visit_service FOREIGN KEY ( visit_id )
        REFERENCES visit ( visit_id );

ALTER TABLE visit
    ADD CONSTRAINT visit_visit_generate_follow_up FOREIGN KEY ( visit_id_follow_up )
        REFERENCES visit ( visit_id );

spool off
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             33
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
